# Project Metadata for XYZ Automated Table 4 - Design and Manufacture
# Version: 1
# Derived from: 260046-SI-99-ActionLaser-LVDTReplacement

[document]
type = "Quotation"
number = "SI-QU-260052-01"
issue_date = "2026-01-29"
issue_date_formatted = "Wed 29-01-2026"
expiry_date = "2026-02-28"
expiry_date_formatted = "Sat 28-02-2026"

[project]
id = "260052-SI"
title = "XYZ Automated Table 4 - Design and Manufacture"
base_price = 50285.00
multiplier = 1.14
total_price = 57325.70

[client]
name = "Actionlaser Pty Limited"
short_name = "ActionLaser"
address_line1 = "Unit 1, 32 Leighton Place"
address_line2 = "Hornsby, NSW 2077"

[client.contact]
salutation = "Mr"
title = "Production Manager"
email = "davidp@actionlaser.com"
phone = "0492 940 025"

[client.contact.name]
first = "David"
last = "Pask"

[simplemotion]
entity = "SimpleMotion.Projects Pty Ltd"
short_name = "SimpleMotion"
abn = "67 126 272 197"
address_line1 = "20-22 Hampstead Rd"
address_line2 = "AUBURN NSW 2144, Australia"
phone = "+61 2 9046 1400"
website = "www.simplemotion.com"

[simplemotion.author]
name = "Greg Gowans"
pronouns = "he/him"
title = "Managing Director"
mobile = "+61 418 888 604"
email = "greg.gowans@simplemotion.com"
